name: "Auto Format Issue Title"

on:
  issues:
    types: [opened, labeled]

permissions:
  issues: write

jobs:
  format_title:
    runs-on: ubuntu-latest
    steps:
      - name: Format issue title
        uses: recursivezero/template/.github/actions/format-issue-title@v2.5
        with:
          prefix: TZF
